---
- hosts: localvm-tunnel
  become: true
  tasks:
    - name: Print OS info
      ansible.builtin.debug:
        msg: "Running on {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Install Apache2
      ansible.builtin.package:
        name: apache2
        state: present
