---
- name: Configure localvm-tunnel
  hosts: localvm-tunnel
  become: true   # Use sudo for tasks that need root
  gather_facts: yes

  tasks:
    - name: Print OS information
      ansible.builtin.shell: uname -a
      register: os_info

    - name: Show OS information
      ansible.builtin.debug:
        msg: "{{ os_info.stdout }}"

    # Example task: install Apache2
    - name: Install Apache web server
      ansible.builtin.package:
        name: apache2
        state: present

    # Example task: ensure service is running
    - name: Ensure Apache is running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
