---
- name: Configure local VM
  hosts: localvm-tunnel
  become: true
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Print OS information
      ansible.builtin.command: lsb_release -a
      register: os_info

    - name: Show OS info
      ansible.builtin.debug:
        var: os_info.stdout_lines
